title: "Couple Memories"
baseURL: /
params:
  layout_style: grid
  palette: orange
  header:
    title: "Couple Memories"
    #logo_img: images/logo.svg
    #logo_img_alt: CpMe Logo
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Timeline
        url: /timeline
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
  footer:
    content: >-
      &copy stackbit, Sito carino per una coppia carina :)
    has_social: false
    social_links:
      - label: Twitter
        url: 'https://twitter.com/'
        style: icon
        icon_class: twitter
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: instagram
        new_window: true
      - label: GitHub
        url: 'https://github.com/'
        style: icon
        icon_class: github
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: icon
        icon_class: linkedin
        new_window: true
      - label: DEV
        url: 'https://dev.to/'
        style: icon
        icon_class: dev
        new_window: true
    has_subscribe: false
    subscribe_title: Subscribe for new updates
    subscribe_content: >-
      Subscribe to my email newsletter to receive useful articles and special
      offers. This monthly email is sent out on the first of every month.
    subscribe_action: /subscribe-success
  domain: 'https://oceanic-lavender-b4a2b.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
